sonar_ip: 192.168.1.10
sonar_port: 23
local_ip: 192.168.1.132
local_port: 2002
subnet_mask: 255.255.255.0
recv_timeout_ms: 500
duration_sec: 0
output_dir: output
save_raw_packets: false
save_csv: true
save_bin: false
dump_decoded: false
once: false
queue_capacity: 256
work_status: 0
range_index: 20
start_gain: 10
logf: 1
absorption: 0
power: 10
pulse_length: 10
profile_min_range_m: 0.0
dhcp_type: 0
device_ip: 192.168.1.10
ip_pool_start: 132
calibrate: 0
switch_delay: 0
frequency_index: 5
